KMSFanHome2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KMSFanHome2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {          
            ViewBag.Message = "修改此模板以快速启动你的 ASP.NET MVC 应用程序。";

            Models.VotedatabaseContext mv = new Models.VotedatabaseContext();

            return View(mv.users.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "你的应用程序说明页222222222。";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "你的联系方式页。";

            return View();
        }
    }
}

KMSFanHome2/Controllers/NewVoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KMSFanHome2.Models;

namespace KMSFanHome2.Controllers
{
    public class NewVoteController : Controller
    {
        VotedatabaseContext vc = new VotedatabaseContext(); /*code first实例*/

        //
        // GET: /NewVote/

        /// <summary>
        /// 新投票系统首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {

            /*多表查询*/
            var temp = from u in vc.count_voting
                       join uu in vc.vote_details on u.VoteTypeId equals uu.voteId
                       select new
                       {
                           name = uu.memo,
                           voteItem = u.selectname
                       };

            //var list = new List<ModelList>() { 
                
            //};

            /*单表查询*/
            var singleTemp = from u in vc.vote_details
                             select new {memo=u.memo };


            List<ModelListComplex> list = new List<ModelListComplex>();
            //foreach (var i in temp)
            //{

            //    ModelListComplex mlc = new ModelListComplex();
               
            //    mlc.voteName = i.name;

            //    if (mlc.voteDetail == null)
            //    {
            //        mlc.voteDetail = new List<string>();
            //    }

            //    if (i.voteItem != null)
            //    {
            //        //先新建一个实例
                    
            //        mlc.voteDetail.Add(i.voteItem);
            //    }


            //        list.Add(mlc);
   
            //}

            /*解决了一个投票项名称，多个子投票项的问题*/
            foreach (var i in singleTemp)
            {
                ModelListComplex mlc = new ModelListComplex();

                mlc.voteName = i.memo;

                var temp2 = from u in vc.count_voting
                           
                           join uu in vc.vote_details on u.VoteTypeId equals uu.voteId
                           where u.TypeName == i.memo
                           select new
                           {
                               name = uu.memo,
                               voteItem = u.selectname
                           };

                foreach (var j in temp2)
                {
                    if (mlc.voteDetail == null)
                    {
                        mlc.voteDetail = new List<string>();
                    }
               
                    mlc.voteDetail.Add(j.voteItem);
                
                }

                list.Add(mlc);

            
            }

            return View(list);
        }

        /// <summary>
        /// 增加投票项
        /// </summary>
        /// <returns></returns>
        public ActionResult AddVote()
        {
            return View();
        
        }


        /// <summary>
        /// 新增投票,建立一个父模型，里面包含了2个子模型
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddVote(Models.ModelList d)
        {
            //投票详情表
            vote_details vt = new vote_details() { 
            memo= d.vd.memo,
            isSingle=d.vd.isSingle,

            
            };
            vc.vote_details.Add(vt);
            vc.SaveChanges(); /*有2此保存，第一次保存是保存上面的*/

            //通过上次保存的结果生成voteid，然后插入到下一张表去
            Models.vote_details voteList=  vc.vote_details.Where(p => p.memo == d.vd.memo).FirstOrDefault();

            if (voteList != null)
            {
                //投票具体项表

                foreach(var c in d.cv)
                {
                    count_voting cv = new count_voting()
                    {
                        selectname = c.selectname,
                        VoteTypeId = voteList.voteId,
                        TypeName = voteList.memo
                    };

                    vc.count_voting.Add(cv);

                    vc.SaveChanges();
                
                
                }


            
            }

            return RedirectToAction("Index", "Home"); /*回到最初的原始界面*/
        
        }

    }
}

KMSFanHome2/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KMSFanHome2.Services;
using KMSFanHome2.Models;
using System.Data.Entity;
using System.Data;

namespace KMSFanHome2.Controllers
{
    /// <summary>
    /// 投票系统的控制器
    /// </summary>
  
    public class VoteController : Controller
    {
        VotedatabaseContext vc=new VotedatabaseContext();

        /// <summary>
        /// 接口声明
        /// </summary>
        public IVoteServices voteService { get; set; }

        //
        // GET: /Vote/

        public ActionResult Index()
        {
            var list = vc.users.ToList();

            return View(list);
        }


        /// <summary>
        /// 获得用户列表
        /// </summary>
        /// <returns></returns>
        public ActionResult GetUsersList()
        {


            return this.View();
        }

        public ActionResult VoteUser()
        {
          
            return this.View();
        
        }

        /// <summary>
        /// 增加投票
        /// </summary>
        /// <param name="?"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VoteUser(Models.user u)
        { 

            //检查用户名是否重复
            var check_username = vc.users.Where(p => p.username == u.username).FirstOrDefault();

            if (check_username != null)
            {
                ModelState.AddModelError("username", "用户名已经被注册！");
                return View();
            }
            else
            {
                //var member=vc.users.Where
                user ur = new user()
                {
                    username = u.username,
                    passwd = u.passwd

                };
                vc.users.Add(ur);
                vc.SaveChanges();
                return RedirectToAction("Index", "Home");
            }


        
        }
        public ActionResult DeleteUser(int  id=0)
        {
            //var check_user = vc.users.Where(p => p.username == username).SingleOrDefault();
            //if (check_user != null)
            //{
            //    vc.users.Remove(check_user); //删除用户
            //    vc.SaveChanges();
            //    return View();

            //}
            //else
            //{
            //    ModelState.AddModelError("username", "该用户不存在");
            //    return View();
            
            //}
            Models.user u = vc.users.Find(id);
            if (u == null)
            {

                return HttpNotFound();
            }
            else
            {
                vc.users.Remove(u);
                vc.SaveChanges();
                return RedirectToAction("Index");
            
            }
        }

        /// <summary>
        /// 编辑用户
        /// </summary>
        /// <param name="id">用户ID</param>
        /// <returns></returns>
        public ActionResult Edit(int id = 0)
        {
            Models.user u = vc.users.Find(id);

            if (u == null)
            {
                return HttpNotFound();
            }

            return View(u);
        
        }

        [HttpPost]
        public ActionResult Edit(Models.user u)
        {
            if (ModelState.IsValid)
            {
                vc.Entry(u).State = EntityState.Modified;
                vc.SaveChanges();
                return RedirectToAction("Index");
            
            }

            return View(u);
        
        }



        
    }
}

KMSFanHome2/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>
</article>

<aside>
    <h3>副标题</h3>
    <p>
        使用此区域可提供附加信息。
    </p>
    <ul>
        <li>@Html.ActionLink("主页", "Index", "Home")</li>
        <li>@Html.ActionLink("关于", "About", "Home")</li>
        <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
    </ul>
</aside>

KMSFanHome2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "联系方式";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>电话</h3>
    </header>
    <p>
        <span class="label">主要:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">下班后:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>电子邮件</h3>
    </header>
    <p>
        <span class="label">支持:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">营销:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">常规:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>地址</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

KMSFanHome2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "主页";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                若要了解有关 ASP.NET MVC 的详细信息，请访问
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>。
                该页提供 <mark>视频、教程和示例</mark> 以帮助你充分利用 ASP.NET MVC。
                如果你对 ASP.NET MVC 有任何疑问，请访问
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">我们的论坛</a>。
            </p>
            <div>@Html.ActionLink("Test", "UsingViewData","Test")</div>

            <div>@Html.ActionLink("添加用户","VoteUser","Vote")</div>

            <div>@Html.ActionLink("用户详情","Index","Vote")</div>

            <hr />

            <div>@Html.ActionLink("添加投票","AddVote","NewVote")</div>

            <div>@Html.ActionLink("投票详情","Index","NewVote")</div>


        </div>
    </section>
}
<h3>下面是我们的建议:</h3>
<ol class="round">
    <li class="one">
        <h5>开始使用</h5>
        ASP.NET MVC 为你提供了一种用于生成动态网站的方式，
        该方式基于模式，十分强大，使你可以清晰地分离各种考虑因素，让你能够完全控制标记，
            以便进行灵活而有趣的开发。ASP.NET MVC 包括许多功能，你可以使用这些功能进行
            TDD 友好的快速开发，以创建使用
            最新 Web 标准的复杂应用程序。
            <a href="http://go.microsoft.com/fwlink/?LinkId=245151">了解详细信息...</a>
    </li>

    <li class="two">
        <h5>添加 NuGet 程序包并快速开始编码</h5>
        通过 NuGet，可以轻松地安装和更新免费的库和工具。
            <a href="http://go.microsoft.com/fwlink/?LinkId=245153">了解详细信息...</a>
    </li>

    <li class="three">
        <h5>查找 Web 宿主</h5>
        你可以轻松找到所提供的功能和价格
      都适合你应用程序的 Web 宿主公司。
            <a href="http://go.microsoft.com/fwlink/?LinkId=245157">了解详细信息...</a>
    </li>
</ol>